url: "http://justincai.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "justin cai"
permalink: /blog/:year/:month/:day/:title/
plugins:
  - jekyll-sitemap
markdown: kramdown
kramdown:
    math_engine: katex
    math_engine_opts: {}
exclude: ["upload.ps1", "README.md"]